POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtYXJpYW5pIiwiaWQiOiI2MTFlNDJiNDNjNDkwYjJmMjNmMWU1MDEiLCJpYXQiOjE2MjkzNzgxNzd9.4c1hZEfNjfrznqbNDRfq81gPxMUPydsw6_v3vhPsLDg

{
    "title": "Interacción Digital with JWT",
    "author": "Ariel Mariani",
    "url": "http://www.interacciondigital.net/"
}